### ISSUE TITLE
Update W3C page 

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#237]
Update: How can we improve our W3C page?

- [ ] verify and add (if necessary) links to the omigroup home page 
- [ ] welcome message for new sign-ups on w3c to help point them in the right direction to get involved 
- [ ] assign a lead to read the emails and keep in touch with new members 
- [ ] Is there a way to tie in the welcome bot? #234 

---------------------

The W3C page may not be clear and up to date on how to get involved. For one, there are comments asking how to get started. We may benefit from someone moderating the W3C page regularly. 
Furthermore, the page doesn't capture who founded the group accurately. It may be incomplete or due to a process many of us skipped. 

<details>
<summary>See image</summary>

![Screenshot_20220526-135103.png](https://user-images.githubusercontent.com/63426722/170482862-68ff8545-ef50-4fa1-a61a-3f44a91002c4.png)

</details>

**Comment by mrmetaverse** [comment]
Updating this ticket: Can we improve documentation with better links to our website? 

![image](https://user-images.githubusercontent.com/63426722/186266606-29434e20-bf8e-4d14-960b-a8e0982cc256.png)

**Comment by mrmetaverse** [comment]
BUMP, and semi-urgent...
